language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - PYMYSQL_VERSION=0.6.7

install:
  - pip install PyMySQL==$PYMYSQL_VERSION . pytest mock codecov

script:
  - coverage run --source mycli -m py.test

